import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/lib/ui/provider";


export const metadata: Metadata = {
  title: "ADVOCAID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
